const FilterData = [
    {
        id:1,
        img:'../src/img/frut1.png',
        name:'Granate',
        price:'38$',
        amount:'5kg',
        category:'Frut',
        
    },
    {
        id:2,
        img:'../src/img/frut2.jpg',
        name:'Orange',
        price:'22$',
        amount:'7kg',
        category:'Frut'
    },
    {
        id:3,
        img:'../src/img/frut3.jpg',
        name:'Strawberry',
        price:'76$',
        amount:'10kg',
        category:'Frut'
    },
    {   
        id:4,
        img:'../src/img/frut4.jpg',
        name:'Apple',
        price:'16$',
        amount:'11kg',
        category:'Frut'
    },
    {
        id:5,
        img:'../src/img/vegi1.jpg',
        name:'Cucumber',
        price:'8$',
        amount:'5kg',
        category:'Vegis'
    },
    {
        id:6,
        img:'../src/img/vegi2.jpg',
        name:'Brocoly',
        price:'26$',
        amount:'5kg',
        category:'Vegis'
    },
    {
        id:7,
        img:'../src/img/vegi3.jpg',
        name:'Onion',
        price:'9$',
        amount:'5kg',
        category:'Vegis'
    },
    {
        id:8,
        img:'../src/img/vegi4.jpg',
        name:'Potato',
        price:'29$',
        amount:'5kg',
        category:'Vegis'
    },
    {
        id:9,
        img:'../src/img/acc1.jpg',
        name:'Pensil',
        price:'24$',
        amount:'100',
        category:'Accesory'
    },
    {
        id:10,
        img:'../src/img/acc2.jpg',
        name:'Hats',
        price:'88$',
        amount:'10',
        category:'Accesory'
    },
    {
        id:11,
        img:'../src/img/acc3.jpg',
        name:'Boocks',
        price:'450$',
        amount:'100',
        category:'Accesory'
    },
    {
        id:12,
        img:'../src/img/acc4.jpg',
        name:'Backpack',
        price:'380$',
        amount:'10',
        category:'Accesory'

    },
]

export default FilterData